version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  ignore:
  - dependency-name: "@types/node"
  - dependency-name: "@types/vscode"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
